# Generated by Django 5.0.14 on 2025-04-14 17:33

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auctions", "0002_alter_auction_author_alter_bid_bidder_comment"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="auction",
            options={"ordering": ["-created"]},
        ),
        migrations.AlterModelOptions(
            name="bid",
            options={"ordering": ["-created"]},
        ),
        migrations.AddField(
            model_name="auction",
            name="figure_url",
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AddIndex(
            model_name="auction",
            index=models.Index(
                fields=["-created"], name="auctions_au_created_ad8912_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="bid",
            index=models.Index(
                fields=["-created"], name="auctions_bi_created_b7b744_idx"
            ),
        ),
    ]
