# Generated by Django 5.0.14 on 2025-04-15 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auctions", "0004_profile"),
    ]

    operations = [
        migrations.AlterField(
            model_name="auction",
            name="figure_url",
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
